### ISSUE TITLE
Change the plugin name

### ISSUE THREAD

**Issue by karlprieb** [karlprieb/babel-plugin-add-import-extension#5]
What do you guys think of change this plugin name as now it deals with exports too?

@Banou26 @FezVrasta

**Comment by FezVrasta** [comment]
I think this name is very clear and makes the plugin easy to find.

`export ... from` is not very commonly used so I don't think it's going to be a problem if this functionality is not "exposed" in the name.

**Comment by Banou26** [comment]
Doesn't matter, exports obviously deal with imports at the same time, it doesn't need to change from my POV.

**Comment by karlprieb** [comment]
Make sense. Thank you, guys!
