### ISSUE TITLE
Feature Request: import path replace option

### ISSUE THREAD

**Issue by Banou26** [karlprieb/babel-plugin-add-import-extension#6]
*continuing https://github.com/karlprieb/babel-plugin-add-import-extension/issues/3#issuecomment-574395942*

We should implement a way to replace the import paths.

Is it okay to make both a simple JSON only valid regex replacer for `.babelrc` files
```json
"(.+)\.ts$": "\\1.js"
```

And a programmatic replacer which can be used in a `.babelrc.js` file ?
```js
({ filename, dirname, importPath, ...ect }) => 'newImportPath'
```

Or should we keep the plugin simple and only allow for regex only replacements ?

**Comment by karlprieb** [comment]
Hmm, it's ok to use the regex replacer, it's already powerful, but I thought that we can make something ever simpler like set the `extension` and an option like `replaceExistentExtension`.

Example: 
```
plugins: [
  ['babel-plugin-add-import-extension', {
      extension: 'jsx' ,
      replaceExistentExtension: true
    }
  ]
]
```

So in the plugin we will watch for this option and if there's already an extension on the import path we can replace it with the set extension on the options. What do you think? It's too simple for your needs?
